sudo: required
services:
  - docker

before_install:
  - docker build -t zamlythaha/react-test -f ./client/Dockerfile.dev ./client

script:
  # - docker run zamlythaha/docker-react npm run test -- --coverage
  - docker run -e CI=true zamlythaha/react-test npm test

after_success:
 - docker build -t zamlythaha/multi-client ./client
 - docker build -t zamlythaha/multi-nginx ./nginx
 - docker build -t zamlythaha/multi-server ./server
 - docker build -t zamlythaha/multi-worker ./worker
 # Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Push images to docker hub
 - docker push zamlythaha/multi-client
 - docker push zamlythaha/multi-nginx
 - docker push zamlythaha/multi-server
 - docker push zamlythaha/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-561421712725"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_USER_ID
  secret_access_key:
    secure: "$AWS_SECRET"

